WIP: Noetic bashscript updates
prl-mushr/mushr pull request #78
Opened 2022-04-21 23:11 UTC by schmittlema

- removed adding things to .bashrc and replaced with a autogenerated mushr_noetic script
- added pushd/popd commands for running the install script from other directories
- removed creating the catkin_ws
- removed sudo pip install to support virtual envs
- changed variables to have MUSHR_ prefix
- removed xhost +x
- removed SHELL_PROFILE variable

2022-04-26 05:00 UTC, brianhou requested changes
Made some minor nitpicks. Let me know when I should test these instructions again!

2022-04-26 05:00 UTC, brianhou commented on mushr_utils/install/mushr_install.bash
> +if [[ $MUSHR_OS_TYPE != "Darwin" ]]; then
Should this be `== "Linux"` to match the condition above?

2022-04-26 05:00 UTC, brianhou commented on mushr_utils/install/mushr_install.bash
> +export MUSHR_WS_PATH=$(pwd | sed 's:/catkin_ws.*::')
Now that the `catkin_ws` is being created correctly, is `sed` really necessary? Or is there a relative path that we can use?

2022-04-26 05:00 UTC, brianhou commented on mushr_utils/install/mushr_install.bash
> +cd mushr/mushr_utils/install/ && export MUSHR_INSTALL_PATH=$(pwd)
Is this still necessary?

2022-04-26 05:00 UTC, brianhou commented on mushr_utils/install/mushr_install.bash
> +    echo "docker-compose -f \$MUSHR_INSTALL_PATH/\$MUSHR_COMPOSE_FILE run -p 9090:9090 mushr_noetic bash" >> ${MUSHR_INSTALL_PATH}/mushr_noetic
This could be replaced with a [heredoc](https://stackoverflow.com/questions/2953081/how-can-i-write-a-heredoc-to-a-file-in-bash-script).

2022-04-26 05:00 UTC, brianhou commented on mushr_utils/install/mushr_install.bash
> +  touch $MUSHR_WS_PATH/catkin_ws/src/mushr/mushr_hardware/realsense/realsense2_camera/CATKIN_IGNORE
```suggestion
  for ignored_package in push_button_utils ydlidar realsense/realsense2_camera; do
    touch $MUSHR_WS_PATH/catkin_ws/src/mushr/mushr_hardware/${ignored_package}/CATKIN_IGNORE
  done
```

2022-04-26 05:00 UTC, brianhou commented on mushr_utils/install/mushr_install.bash
> +    export MUSHR_OS_TYPE=robot
Is this needed for pulling the right Docker image? If so, maybe `MUSHR_IMAGE` would be a better name across the board?

2022-04-26 05:00 UTC, brianhou commented on mushr_utils/install/mushr_install.bash
> +    sudo mv ${MUSHR_INSTALL_PATH}/mushr_noetic /usr/local/bin/
I wonder whether it's better to have a symlink, rather than moving the script. The condition on L113 seems like it'll never be true otherwise.

2022-04-28 21:11 UTC, schmittlema commented on mushr_utils/install/mushr_install.bash
> +    export MUSHR_OS_TYPE=robot
the tags are x86_64, Darwin, and robot. Since they are delineated by OS type I though it was a better descriptor than MUSHR_IMAGE

2022-04-28 21:17 UTC, schmittlema commented on mushr_utils/install/mushr_install.bash
> +export MUSHR_WS_PATH=$(pwd | sed 's:/catkin_ws.*::')
sed seems cleaner to me than using a bunch of dots. I replaced pwd with MUSHR_INSTALL_PATH though.

2022-04-28 21:25 UTC, brianhou commented on mushr_utils/install/mushr_install.bash
> +    export MUSHR_OS_TYPE=robot
I guess I don't think of "robot" as an OS -- I'd be more fine if it were renamed to the appropriate OS.

2022-05-31 19:25 UTC, merged